# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('janus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegroup',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, to='janus.ProfileGroup'),
        ),
        migrations.AlterField(
            model_name='profilepermission',
            name='groups',
            field=models.ManyToManyField(blank=True, to='janus.ApplicationGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='profilepermission',
            unique_together=set([('profile', 'application')]),
        ),
    ]
