# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus', '0003_applicationextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationextension',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
