# Generated by Django 2.1.5 on 2019-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus', '0005_applicationextension_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationextension',
            name='profile_replace_json',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
