# Generated by Django 2.1.5 on 2019-01-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus', '0006_applicationextension_profile_replace_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
