# Generated by Ianni 1.0.0 on 2022-08-08 kurz vor 12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus', '0008_auto_20190730_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='GroupPermission',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ProfileGroup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
