# Generated by Django 3.2.15 on 2022-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus', '0008_auto_20190730_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepermission',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
